"""Persistence behind one interface.

Two implementations: `supabase` for production, and `memory` for dry runs, tests and the
web app's local fixtures. The pipeline only ever talks to this protocol, so every stage can
be exercised end to end without a database or network.
"""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from agent.models import Analysis, Card, Draft, Ranked, Reader
from agent.threads import ThreadPlan


class Store(Protocol):
    # run bookkeeping
    def start_run(self) -> int: ...
    def finish_run(self, run_id: int, status: str, stats: dict, error: str | None) -> None: ...
    def record_stage(self, run_id: int, stage: str, status: str, started: datetime,
                     finished: datetime, detail: dict) -> None: ...
    def record_llm_call(self, run_id: int, record: dict) -> None: ...

    # sources
    def sources(self, defaults: list[dict]) -> list[dict]: ...
    def source_result(self, source_id: str, ok: bool, error: str | None, now: datetime) -> None: ...

    # shared editorial data
    def upsert_articles(self, run_id: int, drafts: list[Draft], now: datetime) -> None: ...
    def save_texts(self, drafts: list[Draft]) -> None: ...
    def thread_context(self, now: datetime) -> list[dict]: ...
    def save_analyses(self, run_id: int, analyses: list[Analysis], now: datetime) -> None: ...
    def apply_threads(self, plan: ThreadPlan, now: datetime) -> dict: ...

    # readers
    def readers(self) -> list[Reader]: ...
    def events_since(self, user_id: str, since: str | None) -> list[dict]: ...
    def article_signals(self, article_ids: set[int]) -> dict[int, dict]: ...
    def save_taste(self, user_id: str, weights: dict[str, float], evidence: dict[str, int],
                   now: datetime) -> None: ...
    def edition_cards(self, now: datetime) -> list[Card]: ...
    def already_shown(self, user_id: str, edition_date: str) -> set[int]: ...
    def thread_engagement(self, user_id: str, thread_ids: set[int]) -> list[dict]: ...
    def save_edition(self, user_id: str, run_id: int | None, edition_date: str,
                     ranked: list[Ranked], candidate_count: int) -> int: ...
    def edition_for_email(self, user_id: str, edition_date: str) -> dict | None: ...
    def mark_emailed(self, edition_id: int, now: datetime) -> None: ...


def open_store(kind: str, path: str | None = None) -> Store:
    if kind == "supabase":
        from agent.store.supabase_store import SupabaseStore
        return SupabaseStore()
    if kind == "memory":
        from agent.store.memory_store import MemoryStore
        return MemoryStore(path)
    raise ValueError(f"unknown store {kind!r}")
